import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "./components/shared/Footer";
import { Header } from "./components/shared/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
          
                
        
      </body>
    </html>
  );
}
